"""
    CechCore_jll

JLL package providing pre-built binaries of the TopoTS Čech filtration
C++ library (libcech) for all supported platforms.

This package is generated by BinaryBuilder.jl and follows the JLL
convention: it exports `libcech` (a `String` path to the shared library)
and `libcech_handle` (an open `Libdl` handle).

# Installation
```julia
]add CechCore_jll
```

# Usage (via TopoTS)
```julia
using TopoTS
# CechCore_jll is loaded automatically as a weak dependency.
# Once installed, :cech filtration is available without any compilation:
dgms = persistent_homology(emb; filtration=:cech)
```

# Direct usage
```julia
using CechCore_jll
ver = unsafe_string(ccall((:cech_version, libcech), Ptr{Cchar}, ()))
# "TopoTS-CechCore-1.0.0"
```
"""
module CechCore_jll

using Artifacts, JLLWrappers, Libdl, Pkg

# ── Artifact resolution ───────────────────────────────────────────────────────

# `artifact"CechCore"` is a macro that resolves to the directory where
# the platform-matched tarball was extracted. Julia's Pkg.Artifacts
# machinery handles platform matching and download automatically.
const artifact_dir = @artifact_str("CechCore")

# Platform-correct library filename
const _libname = Sys.iswindows()  ? "cech.dll"       :
                 Sys.isapple()    ? "libcech.dylib"   : "libcech.so"

"""
    libcech :: String

Absolute path to the platform-native `libcech` shared library.
Resolved from the `CechCore` artifact at package load time.
"""
const libcech = joinpath(artifact_dir, "lib", _libname)

# ── Library handle ────────────────────────────────────────────────────────────

"""
    libcech_handle

Open `Libdl` handle to `libcech`, initialised in `__init__`.
Used internally; prefer `ccall((:symbol, libcech), ...)` for direct calls.
"""
const libcech_handle = Ref{Ptr{Cvoid}}(C_NULL)

function __init__()
    # Verify the library exists at the resolved path
    isfile(libcech) || @warn """
    CechCore_jll: library not found at '$libcech'.
    This usually means the artifact was not downloaded correctly.
    Try: `using Pkg; Pkg.instantiate()`
    """

    try
        libcech_handle[] = Libdl.dlopen(libcech)
    catch e
        @warn "CechCore_jll: failed to load '$libcech': $e"
        return
    end

    # Runtime version check
    try
        ver_sym = Libdl.dlsym(libcech_handle[], :cech_version)
        ver = unsafe_string(ccall(ver_sym, Ptr{Cchar}, ()))
        startswith(ver, "TopoTS-CechCore") || @warn(
            "CechCore_jll: unexpected version string '$ver'")
    catch
    end
end

# ── JLLWrappers-style exports ─────────────────────────────────────────────────

export libcech, libcech_handle

"""
    is_available() -> Bool

Return `true` if the library loaded successfully in `__init__`.
"""
is_available() = libcech_handle[] != C_NULL

"""
    cech_version() -> String

Call the C `cech_version()` function and return the version string.
"""
function cech_version()
    is_available() || return "unavailable"
    unsafe_string(ccall((:cech_version, libcech), Ptr{Cchar}, ()))
end

end # module CechCore_jll
