[[CechCore]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "e7f5a211cf1dfe8186a41822c3adbf448685a792"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.aarch64-apple-darwin.tar.gz"
    sha256 = "e9b1074798fd660d0398050ff117417f8b6318bc62a70983f9997e8d3ce1d9a2"

[[CechCore]]
arch = "aarch64"
os = "linux"
libc = "glibc"
cxxstring_abi = "cxx11"
git-tree-sha1 = "956820e8a4314b6c40fa1533ec524372cd3ce3e3"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.aarch64-linux-gnu-cxx11.tar.gz"
    sha256 = "26540a7903c8f306640b7d89df394b02a768f578d8a66d8a76fd877e7f4394a5"

[[CechCore]]
arch = "aarch64"
os = "linux"
libc = "musl"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c5ad152f9dce507bc751ae99b4f879640bd585d"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.aarch64-linux-musl-cxx11.tar.gz"
    sha256 = "85a5e6ef31320b1abe8b1581af123b12a2917b9593d8c377081d8de22a3941ed"

[[CechCore]]
arch = "aarch64"
os = "freebsd"
git-tree-sha1 = "a2428c2fa3b87c7cab4a96e6d3432ef4e43bc34f"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.aarch64-unknown-freebsd.tar.gz"
    sha256 = "9ba0e9c42a703f9d3e4913f9ecb0cc5b5002dd8ba17666432a986c9aae4c23e0"

[[CechCore]]
arch = "armv6l"
os = "linux"
libc = "glibc"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2c81bd4a22bc4ab8137ff69e27f1f08daa4c015"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
    sha256 = "84051048bc5d563d977db8dbf7cd803b594dd8a256a98d365e2c8b5c15c42039"

[[CechCore]]
arch = "armv6l"
os = "linux"
libc = "musl"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a98642035d4498ce38896c34c4c27d1792970419"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
    sha256 = "d9c0ae7b5b5756ecfae682e9a4eb9c58d3d455d0e25814417b5069c7e4e0a77a"

[[CechCore]]
arch = "armv7l"
os = "linux"
libc = "glibc"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "210388dd8c6d64fbd0eba9fb0940484bb16fc209"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
    sha256 = "75fb5af5e3d2ff39ef7cf777604792c31030d2ec5969ec3a287f996b67c76938"

[[CechCore]]
arch = "armv7l"
os = "linux"
libc = "musl"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c09699cf97d1bf3c71168b3de87d74288e265892"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
    sha256 = "43b241ec3037944168d093792fcf7aca313bbf7e9be1195e4e3944ffb8709d99"

[[CechCore]]
arch = "i686"
os = "linux"
libc = "glibc"
cxxstring_abi = "cxx11"
git-tree-sha1 = "832b58c2d9f99eadcf7d94e0e258ea81c61ea709"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.i686-linux-gnu-cxx11.tar.gz"
    sha256 = "f555539f94855b15bb27cfc7b9b76072ea8392f26aa6dd46c67944e4671f8341"

[[CechCore]]
arch = "i686"
os = "linux"
libc = "musl"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fde9e59458c01b25039002f9ce091e68525b5587"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.i686-linux-musl-cxx11.tar.gz"
    sha256 = "e22a565ad2f86536d1c4771d932868069f9ebf8ee0558b4d5a057dfdc3a064c7"

[[CechCore]]
arch = "i686"
os = "windows"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21f900bd77b2bd7eea23d50289f3b8ed0b84143c"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.i686-w64-mingw32-cxx11.tar.gz"
    sha256 = "c2403bcf1f5942a06d9cd7817079a18d1e79b0d8666e27fdfd1dfd50004e03c9"

[[CechCore]]
arch = "powerpc64le"
os = "linux"
libc = "glibc"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c40af173313608792b2ffc4f8fce2076ee9fa42f"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
    sha256 = "d9858051aeec7b1f9fef1486fed636902ce8ed910bf4adf2df323a688159e0d6"

[[CechCore]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "6393798840445fe31b6292d44db884113daa6fbb"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.x86_64-apple-darwin.tar.gz"
    sha256 = "f7be6005828267cf7d7ce242e0882a795cc2b763d633d6941a16af829e08fc13"

[[CechCore]]
arch = "x86_64"
os = "linux"
libc = "glibc"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad21dd83479534b070b39ff319f5b4a4881aa9c9"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.x86_64-linux-gnu-cxx11.tar.gz"
    sha256 = "a108bc30ef33efdbf16b0ead77b0120bcad6cec35077c0e09ae3e2afc1fac080"

[[CechCore]]
arch = "x86_64"
os = "linux"
libc = "musl"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e055eac6d80d4ef23e1ccbfa05713727549c9c55"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.x86_64-linux-musl-cxx11.tar.gz"
    sha256 = "4cf5d32f1586821c34ca1f6aca1f0077665641090220b76285dfd96e6af10270"

[[CechCore]]
arch = "x86_64"
os = "freebsd"
git-tree-sha1 = "f66f0b73b6aba16ac10757bb943214208d5ac0ed"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.x86_64-unknown-freebsd.tar.gz"
    sha256 = "e067f9f107c5c638c601f13c6be3f246094a51fad3c8ea5b719c7970ae8ae976"

[[CechCore]]
arch = "x86_64"
os = "windows"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58fbce4084aae1c7676e8021d8d996d464c3fafd"

    [[CechCore.download]]
    url = "https://github.com/profsms/CechCore_jll.jl/releases/download/CechCore-v1.0.0+0/CechCore.v1.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
    sha256 = "7ebb93d868c27c1d8107202c0a45a0e789130af67abb07ae82399680f38900ae"